# alembic.ini
# Archivo de configuracion principal de Alembic.
 
[alembic]
 
# Ubicacion de la carpeta que contiene env.py y las versiones de migracion.
script_location = %(here)s/alembic
 
# Agrega el directorio actual al sys.path de Python.
prepend_sys_path = .
 
# Separador de rutas segun el sistema operativo.
path_separator = os
 
# URL de conexion FALLBACK a MySQL.
# env.py la sobreescribe en tiempo de ejecucion usando variables del .env.
sqlalchemy.url = mysql+pymysql://root:admin@localhost:3307/biblioteca_db
 
output_encoding = utf-8
 
 
[post_write_hooks]
 
 
[loggers]
keys = root,sqlalchemy,alembic
 
[handlers]
keys = console
 
[formatters]
keys = generic
 
 
[logger_root]
level = WARNING
handlers = console
qualname =
 
 
[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine
 
 
[logger_alembic]
level = INFO
handlers =
qualname = alembic
 
 
[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic
 
 
[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
 